# Generated by Django 5.2.14 on 2026-05-19 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Urbana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_zona', models.CharField(max_length=100)),
                ('tipologia', models.CharField(choices=[('PARCHEGGIO', 'Area di Parcheggio Consentita'), ('VIETATA', 'Zona a Traffico Limitato / Divieto'), ('CANTIERE', 'Cantiere / Strada Chiusa')], max_length=20)),
            ],
            options={
                'verbose_name': 'Area Urbana',
                'verbose_name_plural': 'Aree Urbane',
            },
        ),
        migrations.CreateModel(
            name='Mezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BICI', 'Bicicletta Elettrica'), ('AUTO', 'Automobile'), ('SCOOTER', 'E-Scooter')], max_length=20)),
                ('stato', models.CharField(choices=[('DISPONIBILE', 'Disponibile'), ('PRENOTATO', 'Prenotato'), ('IN_USO', 'In Uso'), ('MANUTENZIONE', 'In Manutenzione')], default='DISPONIBILE', max_length=20)),
                ('batteria', models.IntegerField(help_text='Percentuale di carica (0-100)')),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Mezzi',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('documento', models.CharField(help_text="Codice Fiscale o Carta d'Identità", max_length=20, unique=True)),
                ('patente_verificata', models.BooleanField(default=False)),
                ('sospensione', models.BooleanField(default=False, help_text="Se True, l'utente non può noleggiare mezzi")),
                ('metodo_pagamento', models.CharField(choices=[('CARTA', 'Carta di Credito/Debito'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], default='CARTA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Corsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fine', models.DateTimeField(blank=True, null=True)),
                ('costo_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corse', to='mobility.mezzo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corse', to='mobility.utente')),
            ],
            options={
                'verbose_name_plural': 'Corse',
            },
        ),
    ]
