# Generated by Django 5.2.14 on 2026-05-21 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_urbana',
            name='latitudine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='area_urbana',
            name='longitudine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='area_urbana',
            name='raggio_metri',
            field=models.IntegerField(default=100, help_text="Raggio di estensione dell'area in metri"),
        ),
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(help_text='Descrizione del guasto o del problema')),
                ('data_segnalazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('risolta', models.BooleanField(default=False)),
                ('mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to='mobility.mezzo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to='mobility.utente')),
            ],
        ),
    ]
