# Generated by Django 5.2.14 on 2026-05-21 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_area_urbana_latitudine_area_urbana_longitudine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosizioneGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('corsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percorso_gps', to='mobility.corsa')),
            ],
            options={
                'verbose_name_plural': 'Posizioni GPS',
                'ordering': ['timestamp'],
            },
        ),
    ]
