# Generated by Django 5.2.14 on 2026-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0003_posizionegps'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='codice_sblocco',
            field=models.CharField(blank=True, help_text='Codice di 6 cifre o ID QR Code', max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='scadenza_prenotazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
