# Generated by Django 5.2.14 on 2026-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0004_mezzo_codice_sblocco_mezzo_scadenza_prenotazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_urbana',
            name='tipologia',
            field=models.CharField(choices=[('PARCHEGGIO', 'Area di Parcheggio Consentita'), ('VIETATA', 'Zona a Traffico Limitato / Divieto'), ('CANTIERE', 'Cantiere / Strada Chiusa'), ('RICARICA', 'Stazione di Ricarica')], max_length=20),
        ),
    ]
