# Generated by Django 5.2.14 on 2026-06-23 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0005_alter_area_urbana_tipologia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promozione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Codice da inserire in app (es. ESTATE25)', max_length=20, unique=True)),
                ('tipo_sconto', models.CharField(choices=[('PERCENTUALE', 'Sconto percentuale (%)'), ('FISSO', 'Sconto fisso (€)')], default='PERCENTUALE', max_length=20)),
                ('valore', models.DecimalField(decimal_places=2, help_text='Es: 20 = 20% oppure 2.50 = 2,50€', max_digits=10)),
                ('data_scadenza', models.DateTimeField(help_text='Oltre questa data il codice non è più valido')),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promozione',
                'verbose_name_plural': 'Promozioni',
            },
        ),
        migrations.AddField(
            model_name='corsa',
            name='area_rilascio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rilasci', to='mobility.area_urbana'),
        ),
        migrations.AddField(
            model_name='corsa',
            name='distanza_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ChatTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('risolto', models.BooleanField(default=False, help_text='True quando il ticket è considerato chiuso')),
                ('operatore', models.ForeignKey(blank=True, help_text="Operatore che ha preso in carico/risposto (vuoto se messaggio dell'utente)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_gestiti', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_chat', to='mobility.utente')),
            ],
            options={
                'verbose_name': 'Messaggio Chat / Ticket',
                'verbose_name_plural': 'Chat & Ticket',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='corsa',
            name='promozione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corse', to='mobility.promozione'),
        ),
    ]
