# Generated by Django 5.2.14 on 2026-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0006_promozione_corsa_area_rilascio_corsa_distanza_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='categoria',
            field=models.CharField(choices=[('FRENI', 'Freni'), ('GOMME', 'Gomme / Ruote'), ('BATTERIA', 'Batteria'), ('TELAIO', 'Telaio / Struttura'), ('VANDALISMO', 'Vandalismo'), ('ALTRO', 'Altro')], default='ALTRO', help_text='Tipo di problema segnalato', max_length=20),
        ),
    ]
