# Generated by Django 5.2.14 on 2026-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0007_segnalazione_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatticket',
            name='da_bot',
            field=models.BooleanField(default=False, help_text='True se il messaggio è una risposta automatica del chatbot'),
        ),
        migrations.AddField(
            model_name='utente',
            name='pagamento_circuito',
            field=models.CharField(blank=True, default='', help_text='Es. VISA, Mastercard, PayPal', max_length=20),
        ),
        migrations.AddField(
            model_name='utente',
            name='pagamento_token',
            field=models.CharField(blank=True, default='', help_text='Token restituito dal gateway', max_length=64),
        ),
        migrations.AddField(
            model_name='utente',
            name='pagamento_ultime4',
            field=models.CharField(blank=True, default='', help_text='Ultime 4 cifre della carta', max_length=4),
        ),
    ]
