# Generated by Django 5.2.14 on 2026-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0008_chatticket_da_bot_utente_pagamento_circuito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='stato',
            field=models.CharField(choices=[('DISPONIBILE', 'Disponibile'), ('PRENOTATO', 'Prenotato'), ('IN_USO', 'In Uso'), ('MANUTENZIONE', 'In Manutenzione'), ('BLOCCATO', 'Bloccato da Remoto')], default='DISPONIBILE', max_length=20),
        ),
    ]
